### PR TITLE
Adding cheatsheet to intro

### PR DESCRIPTION
**Pull request by rosiecakes**
Thought this was cool, reject if you don't

### CODE REVIEW

**Comment by santiagobasulto** [comment]
+1 . Do you know a simple way to create our own cheatsheets?

**Comment by rosiecakes** [comment]
I can make one? :D

**Comment by neo1691** [comment]
+1. Nice cheatsheet.

**Comment by santiagobasulto** [comment]
@rosiecakes of course! It'd be neat to have a few on our own. Never thought about that before.

**Pull request merged**
